// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models;

public partial class Supplier
{
    public int SupplierId { get; set; }

    public string CompanyName { get; set; }

    public string ContactName { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}